spring.application.name=backendtest

# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/chama_app?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=pass123!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Use the generic Dialect for Hibernate 7+
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.address=0.0.0.0
